### PR TITLE
minor clean up, some warnings fixed

### PR DESCRIPTION
**Pull request by karasikov**

### CODE REVIEW

**Comment by marekkokot** [comment]
Hi,

Thanks for this PR. I would like to know which compiler and version do you use. 
I ask because the only warning I have noticed is related to int64 cast (I used g++7.2.0 as far as I remember), which I always forget to fix :(.
The remaining warnings do not appear on my compiler.
The trick with std::ignore is interesting, but after a while of googling one may found this thread https://stackoverflow.com/questions/39745817/stdignore-for-ignoring-unused-variable
There is a couple of arguments against using std::ignore for warning suppression, that seems to be valid.

**Comment by karasikov** [comment]
I use gcc 5.5.0 with `-std=c++14 -Wall -Wextra -Werror` flags.
When I include the KMC API I get those warnings that are treated as errors in my case.

> The trick with std::ignore is interesting, but after a while of googling ...

I think you are right and omitting the variable name might look nicer.

**Comment by marekkokot** [comment]
Could you please check if it compiles after last commit (I checked on g++5.4.0 and it works).

**Comment by karasikov** [comment]
Thanks, it works.

**Pull request closed without merging**
